micronaut:
  application:
    name: micronautDataPageable
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
