micronaut:
  application:
    name: micronautDataPageable
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3

logger:
  levels:
    com.example: TRACE
    io.micronaut.http: DEBUG
    io.micronaut.data.sql.query: TRACE
